spring.application.name=backend-inspectoria
server.port=8080
logging.file.name=backend.log

# ==========================================================
# OPCIÓN 1: H2 (Base de Datos en Memoria)
# No requiere configuración previa.
# ==========================================================
spring.datasource.url=jdbc:h2:mem:inspectoria_angular;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Test
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ==========================================================
# OPCIÓN 2: PostgreSQL (Base de Datos Local)
# Requiere crear la base de datos 'inspectoria_angular' en tu CMD.
# Descomenta estas líneas y comenta las de H2 arriba.
# ==========================================================
# spring.datasource.url=jdbc:postgresql://localhost:5432/inspectoria_angular
# spring.datasource.username=postgres
# spring.datasource.password=1234
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
